### ISSUE TITLE
There is a bug preventing antialiased lines from drawing.

### ISSUE THREAD

**Issue by stevenlgreen00** [m0ppers/nuklear-glfw-vulkan#2]
I know this has not been updated in a while, however I found an issue with this demo that would be a simple fix.
The lines are not being drawn properly due to cull settings.

in file: nuklear-glfw-vulkan.h
changing:
-        .cullMode = VK_CULL_MODE_BACK_BIT,
+      .cullMode = VK_CULL_MODE_NONE,

Will allow AA to to draw the lines properly.

-- Steve

**Comment by m0ppers** [comment]
thanks! done!
