### ISSUE TITLE
Willing to make a PR in the nuklear repo?

### ISSUE THREAD

**Issue by dumblob** [m0ppers/nuklear-glfw-vulkan#3]
People are repeatedly [asking about Vulkan backend](https://github.com/Immediate-Mode-UI/Nuklear/issues/410 ) and if you're fine with MIT license, we (Nuklear maintainers) would like to merge this into the upstream repo.

If you're not OK with maintaining this backend directly in the Nuklear repo, we're considering adding a copy of your repo to our repo ourselves (git submodules are prone to submodule disappearing).

Btw. we are also happily granting full access to the upstream repo if someone reviews a few other PRs :wink:.

**Comment by m0ppers** [comment]
I think it still needs quite some work to be really useful in real life scenarios and right now I am not even using it myself :scream: 

I have too many things going on right now to really maintain it :( But I am hereby granting you full permissions (should be covered by unlicense anyway) to just copy the code, relicense it to MIT and integrate it with the nuklear repo :)
